name = "OffsetBuffers"
uuid = "f7638503-9890-43bf-9e84-07b4cb64c368"
authors = ["Victor G. Gumennyy <20798349+sairus7@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CustomUnitRanges = "dc8bdbbb-1ca9-579f-8c36-e416f6a65cce"
